/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class DeptQueryResponse implements Serializable {


    @JsonProperty("BUDGET")
    @ColumnAlias("BUDGET")
    private Integer budget;

    @JsonProperty("DEPT_CODE")
    @ColumnAlias("DEPT_CODE")
    private String deptCode;

    @JsonProperty("DEPT_ID")
    @ColumnAlias("DEPT_ID")
    private Integer deptId;

    @JsonProperty("LOCATION")
    @ColumnAlias("LOCATION")
    private String location;

    @JsonProperty("NAME")
    @ColumnAlias("NAME")
    private String name;

    @JsonProperty("Q1")
    @ColumnAlias("Q1")
    private Integer q1;

    @JsonProperty("Q2")
    @ColumnAlias("Q2")
    private Integer q2;

    @JsonProperty("Q3")
    @ColumnAlias("Q3")
    private Integer q3;

    @JsonProperty("Q4")
    @ColumnAlias("Q4")
    private Integer q4;

    @JsonProperty("TENANT_ID")
    @ColumnAlias("TENANT_ID")
    private Integer tenantId;

    public Integer getBudget() {
        return this.budget;
    }

    public void setBudget(Integer budget) {
        this.budget = budget;
    }

    public String getDeptCode() {
        return this.deptCode;
    }

    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    public Integer getDeptId() {
        return this.deptId;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getQ1() {
        return this.q1;
    }

    public void setQ1(Integer q1) {
        this.q1 = q1;
    }

    public Integer getQ2() {
        return this.q2;
    }

    public void setQ2(Integer q2) {
        this.q2 = q2;
    }

    public Integer getQ3() {
        return this.q3;
    }

    public void setQ3(Integer q3) {
        this.q3 = q3;
    }

    public Integer getQ4() {
        return this.q4;
    }

    public void setQ4(Integer q4) {
        this.q4 = q4;
    }

    public Integer getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DeptQueryResponse)) return false;
        final DeptQueryResponse deptQueryResponse = (DeptQueryResponse) o;
        return Objects.equals(getBudget(), deptQueryResponse.getBudget()) &&
                Objects.equals(getDeptCode(), deptQueryResponse.getDeptCode()) &&
                Objects.equals(getDeptId(), deptQueryResponse.getDeptId()) &&
                Objects.equals(getLocation(), deptQueryResponse.getLocation()) &&
                Objects.equals(getName(), deptQueryResponse.getName()) &&
                Objects.equals(getQ1(), deptQueryResponse.getQ1()) &&
                Objects.equals(getQ2(), deptQueryResponse.getQ2()) &&
                Objects.equals(getQ3(), deptQueryResponse.getQ3()) &&
                Objects.equals(getQ4(), deptQueryResponse.getQ4()) &&
                Objects.equals(getTenantId(), deptQueryResponse.getTenantId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBudget(),
                getDeptCode(),
                getDeptId(),
                getLocation(),
                getName(),
                getQ1(),
                getQ2(),
                getQ3(),
                getQ4(),
                getTenantId());
    }
}
